## List

In [1]:
a = [1,2,3,4,5]
type(a)

list

In [2]:
a.append('Hello')
a

[1, 2, 3, 4, 5, 'Hello']

In [5]:
a[0] + 10 

11

In [7]:
a[-1] + ' World'

'Hello World'

In [8]:
a = [1,3,5,7, 9]
b = [2,4,6,8,10]

In [9]:
#[1 + 2, 3 + 4 ,5 +6 ...]
len(a)

5

In [10]:
for i in range(len(a)):
    print(i)

0
1
2
3
4


In [11]:
for i in range(len(a)):
    print(a[i])

1
3
5
7
9


In [12]:
for i in range(len(a)):
    print(a[i] + b[i])

3
7
11
15
19


In [13]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [14]:
zip(a,b)

In [15]:
for rec in zip(a,b):
    print(rec)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [16]:
for rec in zip(a,b):
    print(rec[0] + rec[1])

3
7
11
15
19


In [17]:
for i,j in zip(a,b):
    print(i + j)

3
7
11
15
19


In [18]:
ary = []
for i,j in zip(a,b):
    ary.append(i + j)
ary

[3, 7, 11, 15, 19]

In [20]:
[i + j for  i,j in zip(a,b)]

[3, 7, 11, 15, 19]

In [22]:
import numpy
na = numpy.array(a)
nb = numpy.array(b)

In [23]:
na + nb

array([ 3,  7, 11, 15, 19])

In [24]:
na * nb

array([ 2, 12, 30, 56, 90])

In [25]:
import numpy as np

In [26]:
na = np.array([1, 2, 3, 4, 5])
na

array([1, 2, 3, 4, 5])

In [27]:
na[0]

1

In [28]:
na[-1]

5

In [29]:
na[1:3]

array([2, 3])

In [30]:
na

array([1, 2, 3, 4, 5])

In [31]:
na > 3

array([False, False, False,  True,  True])

In [32]:
na[na > 3]

array([4, 5])

In [34]:
na = np.array([
[1,2,3,4, 5],
[6,7,8,9, 10]])

In [35]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
na.shape

(2, 5)

In [37]:
na[0,0]

1

In [38]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
na[:,0]

array([1, 6])

In [40]:
na[0,:]

array([1, 2, 3, 4, 5])

In [41]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [42]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
type(na)

numpy.ndarray

In [44]:
a = [1,2,3,4,5, 'hello']
np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U11')

In [46]:
#  [ 1, 2      X    [2,
#    3, 4 ]          3]

#    2 X 2     X     2 * 1
na = np.array([[1,2],[3,4]])
nb = np.array([2,3])
np.dot(na , nb)

array([ 8, 18])

In [47]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', '_numpy_tester', 'abs'

## Pandas

In [48]:
li = [['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',
35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]]

In [49]:
li

[['frank', 'M', 29],
 ['mary', 'F', 23],
 ['tom', 'M', 35],
 ['ted', 'M', 33],
 ['jean', 'F', 21],
 ['lisa', 'F', 20]]

In [50]:
type(li)

list

In [51]:
import numpy as np
np.array(li)

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [52]:
m = np.array(li)
m[:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U5')

In [54]:
m[:,2].astype(int).sum()

161

In [55]:
li = [['name', 'gender', 'age'],['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',
35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]]

In [62]:
na = np.array(li)

In [67]:
na[:,2][1:].astype(int).sum()

161

## Pandas

In [69]:
import pandas as pd

In [71]:
df = pd.DataFrame([['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]])
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [72]:
df.loc[3,0]

'ted'

In [73]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [74]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [76]:
df['age'].mean()

26.833333333333332

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
name      6 non-null object
gender    6 non-null object
age       6 non-null int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes
