## 中英文斷詞

In [1]:
s = 'this is a book'
s.split()

['this', 'is', 'a', 'book']

In [2]:
s2 = 'i love this book'
s2.split()

['i', 'love', 'this', 'book']

In [3]:
s = '酸民婉君也可以報名嗎?'
s.split()

['酸民婉君也可以報名嗎?']

In [7]:
! pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org jieba

  Running setup.py bdist_wheel for jieba: started
  Running setup.py bdist_wheel for jieba: finished with status 'done'
  Stored in directory: D:\Users\nc20\AppData\Local\pip\Cache\wheels\c9\c7\63\a9ec0322ccc7c365fd51e475942a82395807186e94f0522243
Successfully built jieba


distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [9]:
import jieba
s = '酸民婉君也可以報名嗎?'
for l in jieba.cut(s):
    print(l)

Building prefix dict from the default dictionary ...
Dumping model to file cache D:\Users\nc20\AppData\Local\Temp\jieba.cache
Loading model cost 1.431 seconds.
Prefix dict has been built succesfully.


酸民婉君
也
可以
報名
嗎
?


In [10]:
list(jieba.cut(s))

['酸民婉君', '也', '可以', '報名', '嗎', '?']

In [11]:
s = '''林志玲上月閃婚，不諱言渴望生雙胞胎，今網路突然瘋傳一組她小腹隆起的照片，網友紛紛道賀她「有喜」，但大家恐怕要失望了，這組照片其實是去年10月的志玲姊姊！'''
s.split('，')

['林志玲上月閃婚',
 '不諱言渴望生雙胞胎',
 '今網路突然瘋傳一組她小腹隆起的照片',
 '網友紛紛道賀她「有喜」',
 '但大家恐怕要失望了',
 '這組照片其實是去年10月的志玲姊姊！']

In [13]:
import re
re.split('「|」|！|，', s)

['林志玲上月閃婚',
 '不諱言渴望生雙胞胎',
 '今網路突然瘋傳一組她小腹隆起的照片',
 '網友紛紛道賀她',
 '有喜',
 '',
 '但大家恐怕要失望了',
 '這組照片其實是去年10月的志玲姊姊',
 '']

In [15]:
s = '這組照片其實是去年10月的志玲姊姊'
list(jieba.cut(s))

['這組', '照片', '其實', '是', '去年', '10', '月', '的', '志玲', '姊姊']

## Jieba 斷詞

In [17]:
list(jieba.cut(s, cut_all = True))

['這', '組', '照片', '其', '實', '是', '去年', '10', '月', '的', '志', '玲', '姊姊']

In [18]:
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？ 柯P否認", cut_all=True)
print("Full Mode:", "/ ".join(seg_list))


Full Mode: 大/ 巨蛋/ 案/ 對/ 市府/ 同仁/ 下/ 封口/ 封口令/ 口令/ / / / 柯/ P/ 否/ 認


In [19]:
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？ 柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))

Default Mode: 大/ 巨蛋/ 案對/ 市府/ 同仁/ 下/ 封口令/ ？/  / 柯/ P/ 否認


In [23]:
import jieba
jieba.load_userdict('userdict.txt')
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？ 柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))

Default Mode: 大巨蛋/ 案對/ 市府/ 同仁/ 下/ 封口令/ ？/  / 柯P/ 否認


## Jieba 繁體中文版
- https://github.com/ldkrsi/jieba-zh_TW

In [24]:
import zipfile
zip_ref = zipfile.ZipFile('D:/Users/nc20/Downloads/jieba-zh_TW-master.zip', 'r')
zip_ref.extractall('jieba_zh_tw')
zip_ref.close()

In [25]:
import jieba
jieba.load_userdict('userdict.txt')
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？ 柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))

Default Mode: 大巨蛋/ 案對/ 市府/ 同仁/ 下/ 封口令/ ？/  / 柯P/ 否認


In [29]:
import jieba.posseg as pseg
jieba.load_userdict('userdict.txt')
words = pseg.cut("大巨蛋案對市府同仁下封口令？ 柯P否認")
for w in words:
    print(w.word, w.flag)

大巨蛋 N
案 ng
對 p
市府 N
同仁 N
下 POST
封口令 n
？ x
  x
柯P N
否認 v


In [32]:
import jieba
sentence = "大巨蛋案對市府同仁下封口令？ 柯P否認"
words = jieba.tokenize(sentence)
for tw in words:
    print(tw[0], tw[1], tw[2])

大巨蛋 0 3
案對 3 5
市府 5 7
同仁 7 9
下 9 10
封口令 10 13
？ 13 14
  14 15
柯P 15 17
否認 17 19


In [47]:
news = '''
［記者黃旭磊／高雄報導］高市新增1例本土登革熱病例，50多歲婦為第38例患者，發病前曾至幼兒園接送孫子，所幸同住4人並未發生疑似症狀。

高雄市衛生局今天傍晚公布新增病例，三民區寶民里50多歲婦檢驗分型為第4型，患者過去未罹患過登革熱，平時至寶業滯洪公園散步、澄和黃昏市場採買並接送孫子至幼兒園，所幸家人均無疑似症狀。

衛生局副局長林盟喬說，市區確診38例本土登革熱，其中，32例居住於三民區（鼎金里16例、本和里5例、鼎西里4例、鼎強里及安吉里各2例、鼎力里、鼎盛里及寶民里各1例）、1例於前鎮、1例於鳳山、1例於鼓山、1例於路竹、2例於左營菜公里，至於境外確診登革熱病例33例。

病例發生後，防疫團隊至寶民里社區進行採血作業，今晚9點半將於澄和市場噴藥，而疫情至今感染熱區多在三民區，包括金獅湖一帶（24例）、本和里（5例）及安吉里（2例），至於左營區菜公里也有2例，當地自由黃昏市場封閉3天噴藥，已重新開放。
'''

In [48]:
import jieba
jieba.load_userdict('userdict.txt')
words = list(jieba.cut(news))
#words

In [49]:
dic = {}
for w in words:
    if w not in dic:
        dic[w] = 1
    else:
        dic[w] = dic[w] + 1
#dic

In [50]:
#dic.items()
swd = sorted(dic.items(), key=lambda e:e[1], reverse=True)

In [52]:
for k,v in swd[0:30]:
    if len(k) >=2:
        print(k,v)

病例 4
登革熱 3
三民區 3
寶民里 3
新增 2
本土 2
50 2
多歲 2
38 2
患者 2
幼兒園 2
接送 2
孫子 2
所幸 2


### Counter
- https://docs.python.org/3.7/library/collections.html

In [56]:
a = [1,2,2,2,3,3,2,1,2,3,4,5,5,6]
c = Counter(a)
c.most_common()

[(2, 5), (3, 3), (1, 2), (5, 2), (4, 1), (6, 1)]

In [55]:
import jieba
from collections import Counter
jieba.load_userdict('userdict.txt')
words = list(jieba.cut(news))
c = Counter(words)
for k,v in c.most_common(20):
    if len(k) >=2 :
        print(k,v)

病例 4
登革熱 3
三民區 3
寶民里 3
新增 2
本土 2


## TFIDF

In [57]:
a, abb, abc = ["a"], ["a", "b", "b"], ["a", "b", "c"]
D = [a, abb, abc]

In [58]:
import math
#tfidf('a', a, D)
tf = 1/1
idf = math.log(3/3)
tf * idf

0.0

In [59]:
# tfidf('a', abb, D)
tf = 1/3
idf = math.log(3/3)
tf * idf

0.0

In [60]:
# tfidf('a', abc, D)
tf = 1/3
idf = math.log(3/3)
tf * idf

0.0

In [62]:
# tfidf('b', abb, D)
tf = 2/3
idf = math.log(3/2)
tf * idf

0.27031007207210955

In [63]:
# tfidf('b', abc, D)
tf = 1/3
idf = math.log(3/2)
tf * idf

0.13515503603605478

In [64]:
# tfidf('c', abc, D)
tf = 1/3
idf = math.log(3/1)
tf * idf

0.3662040962227032

In [65]:
a = ['a', 'b', 'a', 'c', 'a']
a.count('a')

3

In [68]:
D
ary = []
for doc in D:
    if 'b' in doc:
        ary.append(doc)
len(ary)

2

In [69]:
def tfidf(t, d, D):
    tf = d.count(t) / len(d)
    idf = math.log(len(D)/ len([doc for doc in D if t in doc]))
    return tf * idf

In [71]:
tfidf('b', abb, D)

0.27031007207210955

In [72]:
tfidf('b', abc, D)

0.13515503603605478

In [73]:
tfidf('c', abc, D)

0.3662040962227032

In [74]:
import jieba.analyse
tags = jieba.analyse.extract_tags(news, 3)

In [75]:
tags

['登革熱', '三民區', '寶民里']

## 詞頻矩陣

In [76]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=1)
content = ["How to format my hard disk", " Hard disk format problems "]
X = vectorizer.fit_transform(content)


In [77]:
print(vectorizer.get_feature_names())
print(X.toarray())

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']
[[1 1 1 1 1 0 1]
 [1 1 1 0 0 1 0]]


In [79]:
s = X.toarray()
s[0] - s[1]

array([ 0,  0,  0,  1,  1, -1,  1], dtype=int64)

In [82]:
posts = ['This is a toy post about machine learning. Actually, it contains not much interesting stuff.',
'Imaging databases can get huge.',
'Most imaging databases safe images permanently.',
'Imaging databases store images.',
'Imaging databases store images. Imaging databases store images. Imaging databases store images']

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
#?CountVectorizer
vectorizer = CountVectorizer(min_df=1)

X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape

In [86]:
num_samples

5

In [88]:
num_features

24

In [89]:
vectorizer.get_feature_names()

['about',
 'actually',
 'can',
 'contains',
 'databases',
 'get',
 'huge',
 'images',
 'imaging',
 'interesting',
 'is',
 'it',
 'learning',
 'machine',
 'most',
 'much',
 'not',
 'permanently',
 'post',
 'safe',
 'store',
 'stuff',
 'this',
 'toy']

In [90]:
X_train.toarray()

array([[1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
        1, 1],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0],
       [0, 0, 0, 0, 3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        0, 0]], dtype=int64)

In [91]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])

In [93]:
new_post_vec.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]], dtype=int64)

In [97]:
import scipy as sp
def dist_raw(v1, v2):
    delta = v1-v2
    return sp.linalg.norm(delta.toarray())

In [101]:
dist_raw(new_post_vec, X_train.getrow(0))

3.872983346207417

In [104]:
for i in range(X_train.shape[0]):
    print(posts[i])
    print(dist_raw(new_post_vec, X_train.getrow(i)))
    print('=====================')

This is a toy post about machine learning. Actually, it contains not much interesting stuff.
3.872983346207417
Imaging databases can get huge.
2.0
Most imaging databases safe images permanently.
2.23606797749979
Imaging databases store images.
1.7320508075688772
Imaging databases store images. Imaging databases store images. Imaging databases store images
5.5677643628300215


In [105]:
def dist(v1, v2):
    v1_normalized = v1 / sp.linalg.norm(v1.toarray())
    v2_normalized = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [106]:
for i in range(X_train.shape[0]):
    print(posts[i])
    print(dist(new_post_vec, X_train.getrow(i)))
    print('=====================')

This is a toy post about machine learning. Actually, it contains not much interesting stuff.
1.414213562373095
Imaging databases can get huge.
1.0514622242382672
Most imaging databases safe images permanently.
1.0878894332937856
Imaging databases store images.
1.0
Imaging databases store images. Imaging databases store images. Imaging databases store images
1.0


In [111]:
vectorizer = CountVectorizer(stop_words = 'english')
X_train = vectorizer.fit_transform(posts)

In [112]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])

In [113]:
def dist(v1, v2):
    v1_normalized = v1 / sp.linalg.norm(v1.toarray())
    v2_normalized = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [114]:
for i in range(X_train.shape[0]):
    print(posts[i])
    print(dist(new_post_vec, X_train.getrow(i)))
    print('=====================')

This is a toy post about machine learning. Actually, it contains not much interesting stuff.
1.4142135623730951
Imaging databases can get huge.
0.9194016867619662
Most imaging databases safe images permanently.
1.0514622242382672
Imaging databases store images.
1.0
Imaging databases store images. Imaging databases store images. Imaging databases store images
1.0


In [118]:
print(vectorizer.get_stop_words())

frozenset({'fifty', 'now', 'un', 'more', 'empty', 'were', 'get', 'themselves', 'few', 'since', 'up', 'due', 'latterly', 'name', 'other', 'us', 'rather', 'that', 'no', 'too', 'though', 'well', 'beside', 'to', 'everywhere', 'put', 'either', 'every', 'detail', 'cant', 'first', 'own', 'before', 'back', 'last', 'ours', 'see', 'hers', 'above', 'between', 'its', 'after', 'almost', 'be', 'seem', 'fifteen', 'these', 'he', 'his', 'thru', 'inc', 'latter', 'perhaps', 'co', 'six', 'bottom', 'against', 'it', 'could', 'next', 'serious', 'where', 'may', 'only', 'therein', 'so', 'would', 'about', 'done', 'whither', 'was', 'under', 'who', 'show', 'they', 're', 'whenever', 'of', 'call', 'whereafter', 'which', 'has', 'we', 'wherein', 'down', 'out', 'top', 'please', 'than', 'do', 'namely', 'whoever', 'besides', 'an', 'less', 'nor', 'yourself', 'whatever', 'nine', 'himself', 'she', 'still', 'should', 'whence', 'same', 'anyone', 'formerly', 'while', 'much', 'whereas', 'off', 'during', 'twelve', 'by', 'a', 'a

In [119]:
! pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org nltk

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [120]:
import nltk.stem
s = nltk.stem.SnowballStemmer('english')
s.stem('graphics')


'graphic'

In [121]:
print(s.stem("imaging"))
print(s.stem("image"))
print(s.stem("imagination"))
print(s.stem("imagine"))

imag
imag
imagin
imagin


In [122]:
import nltk.stem
english_stemmer = nltk.stem.SnowballStemmer('english')
class StemmedCountVectorizer(CountVectorizer):
    
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [123]:
from sklearn.feature_extraction.text import CountVectorizer
#?CountVectorizer
vectorizer = StemmedCountVectorizer(min_df=1)

X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape

In [124]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])

In [127]:
print(vectorizer.get_feature_names())

['about', 'actual', 'can', 'contain', 'databas', 'get', 'huge', 'imag', 'interest', 'is', 'it', 'learn', 'machin', 'most', 'much', 'not', 'perman', 'post', 'safe', 'store', 'stuff', 'this', 'toy']


In [129]:
new_post_vec.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]], dtype=int64)

In [130]:
def dist(v1, v2):
    v1_normalized = v1 / sp.linalg.norm(v1.toarray())
    v2_normalized = v2 / sp.linalg.norm(v2.toarray())
    delta = v1_normalized - v2_normalized
    return sp.linalg.norm(delta.toarray())


In [131]:
for i in range(X_train.shape[0]):
    print(posts[i])
    print(dist(new_post_vec, X_train.getrow(i)))
    print('=====================')

This is a toy post about machine learning. Actually, it contains not much interesting stuff.
1.414213562373095
Imaging databases can get huge.
0.8573732768944039
Most imaging databases safe images permanently.
0.7071067811865475
Imaging databases store images.
0.5176380902050415
Imaging databases store images. Imaging databases store images. Imaging databases store images
0.5176380902050415


In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(min_df=1)

X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape

In [136]:
X_train.toarray()

array([[0.26726124, 0.26726124, 0.        , 0.26726124, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.26726124,
        0.26726124, 0.26726124, 0.26726124, 0.26726124, 0.        ,
        0.26726124, 0.26726124, 0.        , 0.26726124, 0.        ,
        0.        , 0.26726124, 0.26726124, 0.26726124],
       [0.        , 0.        , 0.52451722, 0.        , 0.29550385,
        0.52451722, 0.52451722, 0.        , 0.29550385, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.27880274,
        0.        , 0.        , 0.33142212, 0.27880274, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.49487286,
        0.        , 0.        , 0.49487286, 0.        , 0.49487286,
        0.        , 0.        , 0.        , 0.        ],
       [0.   

In [134]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])

In [135]:
for i in range(X_train.shape[0]):
    print(posts[i])
    print(dist(new_post_vec, X_train.getrow(i)))
    print('=====================')

This is a toy post about machine learning. Actually, it contains not much interesting stuff.
1.414213562373095
Imaging databases can get huge.
1.187009812033225
Most imaging databases safe images permanently.
1.2009973044062707
Imaging databases store images.
1.0697577475609328
Imaging databases store images. Imaging databases store images. Imaging databases store images
1.0697577475609328


In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer
class StemmedTfidfVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(TfidfVectorizer,self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

vectorizer = StemmedTfidfVectorizer(min_df=1)

X_train = vectorizer.fit_transform(posts)
num_samples, num_features = X_train.shape

In [138]:
new_post = 'imaging database'
new_post_vec = vectorizer.transform([new_post])

In [139]:
for i in range(X_train.shape[0]):
    print(posts[i])
    print(dist(new_post_vec, X_train.getrow(i)))
    print('=====================')

This is a toy post about machine learning. Actually, it contains not much interesting stuff.
1.4142135623730951
Imaging databases can get huge.
1.0789758507558254
Most imaging databases safe images permanently.
0.9401975637779192
Imaging databases store images.
0.634205801303706
Imaging databases store images. Imaging databases store images. Imaging databases store images
0.634205801303706


In [142]:
import jieba
jieba.load_userdict('userdict.txt')
a = ['柯文哲為了大巨蛋一事找趙藤雄算帳','柯P將不在大巨蛋舉辦世運會']
corpus = [' '.join(jieba.cut(s)) for s in a]
corpus

['柯文哲 為 了 大巨蛋 一事 找 趙藤雄 算帳', '柯P 將不在 大巨蛋 舉辦 世運會']

In [143]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X

<2x9 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [145]:
vectorizer.get_feature_names()

['一事', '世運會', '大巨蛋', '將不在', '柯p', '柯文哲', '算帳', '舉辦', '趙藤雄']

In [144]:
X.toarray()

array([[1, 0, 1, 0, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [146]:
dist(X[0], X[1])

1.2649110640673518

### 處理同義詞

In [161]:
import requests
from bs4 import BeautifulSoup
term ='柯文哲'
res = requests.get('https://zh.wikipedia.org/wiki/{}'.format(term))
soup = BeautifulSoup(res.text,'lxml')
'/'.join([w.text for w in soup.select('.mw-parser-output p')[5].select('b')])

'柯文哲/柯P/KP'

In [163]:
synonym_dic = {}
for s in open('synonym.txt', encoding='utf-8'):
    synonym = s.strip().split('/')
    for w in synonym[1:]:
        synonym_dic[w.lower()] = synonym[0]
synonym_dic

{'柯p': '柯文哲', 'kp': '柯文哲'}

In [164]:
class SynonymCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(SynonymCountVectorizer, self).build_analyzer()
        return lambda doc: (synonym_dic.get(w, w) for w in analyzer(doc))


In [165]:
vectorizer = SynonymCountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['一事', '世運會', '大巨蛋', '將不在', '柯文哲', '算帳', '舉辦', '趙藤雄']


In [166]:
X.toarray()

array([[1, 0, 1, 0, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 0]], dtype=int64)

In [167]:
dist(X[0], X[1])

1.0954451150103321

In [168]:
stopwords = ['為了','一事','將不在']

In [169]:
vectorizer = SynonymCountVectorizer(stop_words=stopwords)
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['世運會', '大巨蛋', '柯文哲', '算帳', '舉辦', '趙藤雄']


In [170]:
X.toarray()

array([[0, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 0]], dtype=int64)

In [171]:
dist(X[0], X[1])

1.0