## List

In [1]:
a = [1,2,3,4,5]
type(a)

list

In [2]:
a.append('Hello')
a

[1, 2, 3, 4, 5, 'Hello']

In [5]:
a[0] + 10 

11

In [7]:
a[-1] + ' World'

'Hello World'

In [8]:
a = [1,3,5,7, 9]
b = [2,4,6,8,10]

In [9]:
#[1 + 2, 3 + 4 ,5 +6 ...]
len(a)

5

In [10]:
for i in range(len(a)):
    print(i)

0
1
2
3
4


In [11]:
for i in range(len(a)):
    print(a[i])

1
3
5
7
9


In [12]:
for i in range(len(a)):
    print(a[i] + b[i])

3
7
11
15
19


In [13]:
for i in range(len(a)):
    print(a[i] * b[i])

2
12
30
56
90


In [14]:
zip(a,b)

In [15]:
for rec in zip(a,b):
    print(rec)

(1, 2)
(3, 4)
(5, 6)
(7, 8)
(9, 10)


In [16]:
for rec in zip(a,b):
    print(rec[0] + rec[1])

3
7
11
15
19


In [17]:
for i,j in zip(a,b):
    print(i + j)

3
7
11
15
19


In [18]:
ary = []
for i,j in zip(a,b):
    ary.append(i + j)
ary

[3, 7, 11, 15, 19]

In [20]:
[i + j for  i,j in zip(a,b)]

[3, 7, 11, 15, 19]

In [22]:
import numpy
na = numpy.array(a)
nb = numpy.array(b)

In [23]:
na + nb

array([ 3,  7, 11, 15, 19])

In [24]:
na * nb

array([ 2, 12, 30, 56, 90])

In [25]:
import numpy as np

In [26]:
na = np.array([1, 2, 3, 4, 5])
na

array([1, 2, 3, 4, 5])

In [27]:
na[0]

1

In [28]:
na[-1]

5

In [29]:
na[1:3]

array([2, 3])

In [30]:
na

array([1, 2, 3, 4, 5])

In [31]:
na > 3

array([False, False, False,  True,  True])

In [32]:
na[na > 3]

array([4, 5])

In [34]:
na = np.array([
[1,2,3,4, 5],
[6,7,8,9, 10]])

In [35]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
na.shape

(2, 5)

In [37]:
na[0,0]

1

In [38]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
na[:,0]

array([1, 6])

In [40]:
na[0,:]

array([1, 2, 3, 4, 5])

In [41]:
na.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [42]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
type(na)

numpy.ndarray

In [44]:
a = [1,2,3,4,5, 'hello']
np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U11')

In [46]:
#  [ 1, 2      X    [2,
#    3, 4 ]          3]

#    2 X 2     X     2 * 1
na = np.array([[1,2],[3,4]])
nb = np.array([2,3])
np.dot(na , nb)

array([ 8, 18])

In [47]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', '_numpy_tester', 'abs'

## Pandas

In [48]:
li = [['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',
35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]]

In [49]:
li

[['frank', 'M', 29],
 ['mary', 'F', 23],
 ['tom', 'M', 35],
 ['ted', 'M', 33],
 ['jean', 'F', 21],
 ['lisa', 'F', 20]]

In [50]:
type(li)

list

In [51]:
import numpy as np
np.array(li)

array([['frank', 'M', '29'],
       ['mary', 'F', '23'],
       ['tom', 'M', '35'],
       ['ted', 'M', '33'],
       ['jean', 'F', '21'],
       ['lisa', 'F', '20']], dtype='<U5')

In [52]:
m = np.array(li)
m[:,2]

array(['29', '23', '35', '33', '21', '20'], dtype='<U5')

In [54]:
m[:,2].astype(int).sum()

161

In [55]:
li = [['name', 'gender', 'age'],['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',
35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]]

In [62]:
na = np.array(li)

In [67]:
na[:,2][1:].astype(int).sum()

161

## Pandas

In [69]:
import pandas as pd

In [71]:
df = pd.DataFrame([['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M',35], ['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]])
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [72]:
df.loc[3,0]

'ted'

In [73]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [74]:
df.columns = ['name', 'gender', 'age']
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [76]:
df['age'].mean()

26.833333333333332

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
name      6 non-null object
gender    6 non-null object
age       6 non-null int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


## Pandas Series

In [78]:
import numpy as np
a = [1,2,3,4,5]
na = np.array(a)
na

array([1, 2, 3, 4, 5])

In [79]:
import pandas as pd
a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [80]:
a = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
a

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [81]:
import pandas as pd
s = pd.Series([42000, 38000, 56000])
s

0    42000
1    38000
2    56000
dtype: int64

In [82]:
import pandas as pd
s = pd.Series([42000, 38000, 56000], index=['John', 'Marry', 'Sam'])
s

John     42000
Marry    38000
Sam      56000
dtype: int64

In [83]:
s = pd.Series({'John':42000,'Marry':38000,'Sam':56000})
s


John     42000
Marry    38000
Sam      56000
dtype: int64

In [84]:
s[2]

56000

In [85]:
s[1:3]

Marry    38000
Sam      56000
dtype: int64

In [86]:
s

John     42000
Marry    38000
Sam      56000
dtype: int64

In [87]:
s['Sam']

56000

In [88]:
s[['Sam', 'John']]

Sam     56000
John    42000
dtype: int64

In [89]:
s < 40000

John     False
Marry     True
Sam      False
dtype: bool

In [90]:
s[s < 40000]

Marry    38000
dtype: int64

In [92]:
criteria = np.array([False, True, True])
s[criteria]

Marry    38000
Sam      56000
dtype: int64

In [93]:
s < 40000

John     False
Marry     True
Sam      False
dtype: bool

In [94]:
cheap = s < 40000

In [95]:
s[cheap]

Marry    38000
dtype: int64

In [97]:
s['Marry'] = 40000

In [98]:
s

John     42000
Marry    40000
Sam      56000
dtype: int64

In [100]:
s[s==40000] = s[s==40000] * 1.1

In [101]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [102]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [103]:
'David' in s

False

In [104]:
'John' in s

True

In [105]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [106]:
s * 0.8

John     33600.0
Marry    35200.0
Sam      44800.0
dtype: float64

In [107]:
np.sqrt(s)

John     204.939015
Marry    209.761770
Sam      236.643191
dtype: float64

In [108]:
s

John     42000
Marry    44000
Sam      56000
dtype: int64

In [110]:
s.max()

56000

In [111]:
s.min()

42000

In [112]:
s.sum()

142000

In [113]:
s.mean()

47333.333333333336

In [114]:
s.describe()

count        3.000000
mean     47333.333333
std       7571.877794
min      42000.000000
25%      43000.000000
50%      44000.000000
75%      50000.000000
max      56000.000000
dtype: float64

In [116]:
s[['Marry', 'Jane']]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:850: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


Marry    44000.0
Jane         NaN
dtype: float64

In [117]:
s[['John','Marry']]

John     42000
Marry    44000
dtype: int64

In [119]:
s2 = s[['Marry', 'Jane']] + s[['John','Marry']]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:850: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


In [121]:
s2.isnull()

Jane      True
John      True
Marry    False
dtype: bool

In [122]:
s2.notnull()

Jane     False
John     False
Marry     True
dtype: bool

## Pandas DataFrame

In [123]:
import pandas as pd
df = pd.DataFrame([['frank', 'M', 29], ['mary'
, 'F', 23], ['tom', 'M', 35],['ted', 'M', 33], ['jean', 'F', 21], ['lisa'
, 'F', 20]])

In [124]:
df

0  1   2
0  frank  M  29
1   mary  F  23
2    tom  M  35
3    ted  M  33
4   jean  F  21
5   lisa  F  20

In [125]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [126]:
df.columns = ['name', 'gender', 'age']

In [127]:
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [128]:
df = pd.DataFrame([['frank', 'M', 29], ['mary', 'F', 23], ['tom', 'M', 35], ['ted','M', 33], ['jean', 'F', 21], ['lisa', 'F', 20]], 
    columns = ['name', 'gender', 'age'])

In [129]:
df

name gender  age
0  frank      M   29
1   mary      F   23
2    tom      M   35
3    ted      M   33
4   jean      F   21
5   lisa      F   20

In [130]:
df = pd.DataFrame([{
    'name':'frank','gender':'M', 'age':29}, \
{'name':'mary','gender':'F', 'age':23}, \
{'name':'tom','gender':'M', 'age':35}, \
{'name':'ted','gender':'M', 'age':33}, \
{'name':'jean','gender':'F', 'age':21}, \
{'name':'lisa','gender':'F', 'age':20}])

In [132]:
df2 = pd.DataFrame([{
    'name':'frank','gender':'M', 'age':29}, \
{'name':'mary','gender':'F', 'age':23}, \
{'name':'tom','gender':'M'}, \
{'name':'ted','gender':'M', 'age':33}, \
{'name':'jean','gender':'F', 'age':21}, \
{'name':'lisa','gender':'F' }])
df2

age gender   name
0  29.0      M  frank
1  23.0      F   mary
2   NaN      M    tom
3  33.0      M    ted
4  21.0      F   jean
5   NaN      F   lisa

In [134]:
# R:      head(df)
# Python: df.head()
df.head()

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean

In [135]:
?df.head()

In [136]:
df.head(3)

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom

In [137]:
df.tail()

age gender  name
1   23      F  mary
2   35      M   tom
3   33      M   ted
4   21      F  jean
5   20      F  lisa

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
age       6 non-null int64
gender    6 non-null object
name      6 non-null object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [139]:
df.describe()

age
count   6.000000
mean   26.833333
std     6.400521
min    20.000000
25%    21.500000
50%    26.000000
75%    32.000000
max    35.000000

In [141]:
df.dtypes

age        int64
gender    object
name      object
dtype: object

In [143]:
df['name']

0    frank
1     mary
2      tom
3      ted
4     jean
5     lisa
Name: name, dtype: object

In [144]:
df[['name', 'age']]

name  age
0  frank   29
1   mary   23
2    tom   35
3    ted   33
4   jean   21
5   lisa   20

In [145]:
df['gender'] == 'M'

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [147]:
df[df['gender']=='M']

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [148]:
df['gender']=='M' 

0     True
1    False
2     True
3     True
4    False
5    False
Name: gender, dtype: bool

In [149]:
df['age'] > 30

0    False
1    False
2     True
3     True
4    False
5    False
Name: age, dtype: bool

In [150]:
(df['gender']=='M' ) & (df['age'] > 30)

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [151]:
df[(df['gender']=='M' ) & (df['age'] > 30)]

age gender name
2   35      M  tom
3   33      M  ted

In [152]:
df[(df['gender']=='M' ) | (df['age'] > 30)]

age gender   name
0   29      M  frank
2   35      M    tom
3   33      M    ted

In [154]:
df['employee'] = True

In [155]:
df

age gender   name  employee
0   29      M  frank      True
1   23      F   mary      True
2   35      M    tom      True
3   33      M    ted      True
4   21      F   jean      True
5   20      F   lisa      True

In [156]:
a = 5
a + 3

8

In [157]:
del a

In [158]:
a + 3

NameError: name 'a' is not defined

In [159]:
del df['employee']

In [161]:
df['employee'] = True

In [166]:
?df.drop

In [167]:
df.drop('employee', axis = 1, inplace=True)

In [168]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [169]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa

In [170]:
df.loc[8] = {'age':20, 'name':'qoo', 'gender': 'M'}

In [171]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa
8   20      M    qoo

In [177]:
df = df.append(pd.DataFrame([{'age':26,'gender':'F','name':'jane'}]),
ignore_index=True)


In [178]:
df

age gender   name
0   29      M  frank
1   23      F   mary
2   35      M    tom
3   33      M    ted
4   21      F   jean
5   20      F   lisa
6   20      M    qoo
7   26      F   jane

In [181]:
df.drop(6, axis = 0, inplace=True )

In [184]:
df.index

Int64Index([0, 1, 2, 3, 4, 5, 7], dtype='int64')

In [186]:
df['userid'] = range(101,108)

In [187]:
df

age gender   name  userid
0   29      M  frank     101
1   23      F   mary     102
2   35      M    tom     103
3   33      M    ted     104
4   21      F   jean     105
5   20      F   lisa     106
7   26      F   jane     107

In [188]:
df.set_index('userid', inplace=True)

In [190]:
df

age gender   name
userid                   
101      29      M  frank
102      23      F   mary
103      35      M    tom
104      33      M    ted
105      21      F   jean
106      20      F   lisa
107      26      F   jane

In [192]:
# loc: get data by index name
df.loc[103]

age        35
gender      M
name      tom
Name: 103, dtype: object

In [193]:
# iloc: get data by index position
df.iloc[2]

age        35
gender      M
name      tom
Name: 103, dtype: object

In [194]:
df.iloc[[1,3,5]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa

In [195]:
df.loc[[102,104,106]]

age gender  name
userid                  
102      23      F  mary
104      33      M   ted
106      20      F  lisa